Repository kraina-ai/srai, pull requests merged in 2022-11, with the labels that each got.

#74 Add GeoparquetLoader
  docs/copy_examples.py
  examples/loaders/README.md
  examples/loaders/files/example.parquet
  examples/loaders/geoparquet_loader.ipynb
  pdm.lock
  pyproject.toml
  srai/__init__.py
  srai/loaders/__init__.py
  srai/loaders/geoparquet_loader.py
  srai/regionizers/_spherical_voronoi.py
  srai/regionizers/voronoi_regionizer.py
  tests/files/example.parquet
  tests/test_geoparquet_loader.py
Labels: enhancement

#75 Add default value for transform function in VoronoiRegionizer
  examples/regionizers/voronoi_regionizer.ipynb
  srai/regionizers/_spherical_voronoi.py
  srai/regionizers/voronoi_regionizer.py
  tests/test_voronoi_regionizer.py
Labels: bug, enhancement

#87 feat: add administrative boundary regionizer
  examples/regionizers/administrative_boundaries_regionizer.ipynb
  examples/regionizers/voronoi_regionizer.ipynb
  pdm.lock
  pyproject.toml
  srai/regionizers/__init__.py
  srai/regionizers/_spherical_voronoi.py
  srai/regionizers/administrative_boundary_regionizer.py
  srai/regionizers/voronoi_regionizer.py
  tests/regionizers/test_administrative_boundary_regionizer.py
Labels: enhancement

#98 ci: fix mike build
  .github/workflows/full-ci.yml
Labels: bug

#82 Improve docs
  README.md
  docs/README.md
  docs/assets/css/font.css
  docs/assets/css/jupyter.css
  docs/assets/css/palette.css
  docs/assets/images/earth.svg
  docs/assets/logos/favicon.ico
  docs/assets/logos/srai-logo-symbol.png
  docs/assets/logos/srai-logo-symbol.svg
  docs/assets/logos/srai-logo-transparent.png
  docs/assets/logos/srai-logo-transparent.svg
  docs/assets/logos/srai-logo.png
  docs/assets/logos/srai-logo.svg
  docs/copy_examples.py
  examples/regionizers/README.md
  examples/regionizers/administrative_boundary_regionizer.ipynb
  mkdocs.yml
Labels: documentation

#76 feat: add IntersectionJoiner
  CHANGELOG.md
  examples/joiners/README.md
  examples/joiners/intersection_joiner.ipynb
  srai/joiners/__init__.py
  srai/joiners/base.py
  srai/joiners/intersection_joiner.py
  tests/joiners/conftest.py
  tests/joiners/test_intersection_joiner.py
Labels: enhancement

#104 ci: add new tag trigger
  .github/workflows/full-ci.yml
Labels: bug

#105 ci: split workflow into 2 files
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
Labels: enhancement

#107 docs: add library metadata
  pyproject.toml
Labels: documentation

#108 ci: add cache to accelerate tests
  .github/workflows/_tests.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
Labels: enhancement
