Repository kraina-ai/srai, pull requests merged in 2023-04, with the labels that each got.

#223 feat: unify folder structure of gtfs2vec with rest of the library
  srai/embedders/__init__.py
  srai/embedders/gtfs2vec/__init__.py
  srai/embedders/gtfs2vec/embedder.py
  srai/embedders/gtfs2vec/model.py
  srai/models/__init__.py
Labels: Skip-Changelog

#220 feat: add contextual count embedder
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  examples/embedders/contextual_count_embedder.ipynb
  examples/embedders/count_embedder.ipynb
  examples/embedders/highway2vec_embedder.ipynb
  examples/joiners/intersection_joiner.ipynb
  examples/loaders/osm_online_loader.ipynb
  examples/loaders/osm_pbf_loader.ipynb
  pdm.lock
  pyproject.toml
  srai/embedders/__init__.py
  srai/embedders/contextual_count_embedder.py
  srai/embedders/count_embedder.py
  srai/embedders/gtfs2vec/embedder.py
  srai/embedders/gtfs2vec/model.py
  srai/embedders/highway2vec/embedder.py
  srai/embedders/highway2vec/model.py
  srai/joiners/intersection_joiner.py
  srai/loaders/gtfs_loader.py
  srai/loaders/osm_loaders/__init__.py
  srai/loaders/osm_loaders/_base.py
  srai/loaders/osm_loaders/filters/__init__.py
  srai/loaders/osm_loaders/filters/_typing.py
  srai/loaders/osm_loaders/filters/base_osm_groups.py
  srai/loaders/osm_loaders/filters/geofabrik.py
  srai/loaders/osm_loaders/filters/hex2vec.py
  srai/loaders/osm_loaders/filters/osm_tags_type.py
  srai/loaders/osm_loaders/filters/popular.py
  srai/loaders/osm_loaders/osm_online_loader.py
  srai/loaders/osm_loaders/osm_pbf_loader.py
  srai/loaders/osm_loaders/pbf_file_downloader.py
  srai/loaders/osm_loaders/pbf_file_handler.py
  srai/loaders/osm_way_loader/constants.py
  srai/loaders/osm_way_loader/osm_way_loader.py
  srai/neighbourhoods/adjacency_neighbourhood.py
  srai/plotting/folium_wrapper.py
  srai/utils/typing.py
  tests/embedders/test_contextual_count_embedder.py
  tests/embedders/test_count_embedder.py
  tests/joiners/test_intersection_joiner.py
  tests/loaders/osm_loaders/filters/test_merge_filter_types.py
  tests/loaders/osm_loaders/test_osm_online_loader.py
  tests/loaders/osm_loaders/test_osm_pbf_loader.py
  tests/neighbourhoods/test_adjacency_neighbourhood.py
Labels: enhancement

#241 docs: change navigation
  docs/.pages
  docs/generate_api.py
  examples/embedders/README.md
  mkdocs.yml
  srai/loaders/__init__.py
Labels: Skip-Changelog

#235 fix: use common interface in joiners and loaders
  srai/joiners/_base.py
  srai/joiners/intersection_joiner.py
  srai/loaders/_base.py
  srai/loaders/geoparquet_loader.py
  srai/loaders/gtfs_loader.py
  srai/loaders/osm_loaders/_base.py
  srai/loaders/osm_loaders/osm_online_loader.py
  srai/loaders/osm_loaders/osm_pbf_loader.py
  srai/loaders/osm_way_loader/osm_way_loader.py
Labels: Skip-Changelog

#242 docs: change docs navigation
  docs/generate_api.py
  srai/plotting/__init__.py
Labels: Skip-Changelog

#215 chore: torch and pytorch-lightning as optional dependencies
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/getting_started/README.md
  pdm.lock
  pyproject.toml
  srai/embedders/gtfs2vec/embedder.py
  srai/embedders/gtfs2vec/model.py
  srai/embedders/highway2vec/embedder.py
  srai/embedders/highway2vec/model.py
  srai/loaders/osm_loaders/pbf_file_downloader.py
  srai/neighbourhoods/_base.py
  srai/utils/_pytorch_stubs.py
  tests/miscellaneous/test_optional_dependencies.py
Labels: enhancement

#254 docs: add edit and view source code on github
  mkdocs.yml
Labels: documentation, Skip-Changelog

#217 feat: OSM Tile Loader
  CHANGELOG.md
  examples/loaders/osm_tile_loader.ipynb
  examples/regionizers/slippy_map_regionizer.ipynb
  pdm.lock
  pyproject.toml
  srai/loaders/__init__.py
  srai/loaders/osm_loaders/__init__.py
  srai/loaders/osm_loaders/osm_tile_data_collector.py
  srai/loaders/osm_loaders/osm_tile_loader.py
  srai/regionizers/__init__.py
  srai/regionizers/slippy_map_regionizer.py
  tests/loaders/osm_loaders/test_osm_tile_data_collector.py
  tests/loaders/osm_loaders/test_osm_tile_loader.py
  tests/miscellaneous/test_optional_dependencies.py
  tests/regionizers/test_slippy_map_regionizer.py
Labels: enhancement

#266 docs: improve readme and examples
  README.md
  examples/embedders/hex2vec_embedder.ipynb
  pyproject.toml
  srai/loaders/osm_loaders/pbf_file_handler.py
Labels: Skip-Changelog

#267 docs: add full usage examples to README
  README.md
Labels: Skip-Changelog

#268 docs: revise readme, copy main to docs
  README.md
  docs/README.md
Labels: Skip-Changelog
