Repository kraina-ai/srai, pull requests merged in 2023-10, with the labels that each got.

#363 Speed up ContextualCountEmbedder operation
  CHANGELOG.md
  srai/embedders/contextual_count_embedder.py
  tests/embedders/test_contextual_count_embedder.py
Labels: hacktoberfest-accepted

#367 feat: add Geofabrik and OSMfr PBF extracts sources
  .pre-commit-config.yaml
  CHANGELOG.md
  pdm.lock
  pyproject.toml
  srai/loaders/download.py
  srai/loaders/osm_loaders/openstreetmap_extracts.py
  srai/loaders/osm_loaders/osm_pbf_loader.py
  srai/loaders/osm_loaders/pbf_file_downloader.py
  tests/loaders/osm_loaders/test_files/monaco.osm.pbf
  tests/loaders/osm_loaders/test_osm_pbf_loader.py
  tests/miscellaneous/test_optional_dependencies.py
Labels: bug, hacktoberfest-accepted

#370 Add option to clip osmpbf files with osmosis and osmconvert tools
  CHANGELOG.md
  srai/geometry.py
  srai/loaders/download.py
  srai/loaders/osm_loaders/openstreetmap_extracts.py
  srai/loaders/osm_loaders/osm_pbf_loader.py
  srai/loaders/osm_loaders/pbf_file_clipper.py
  srai/loaders/osm_loaders/pbf_file_downloader.py
  tests/loaders/osm_loaders/test_osm_pbf_loader.py
Labels: enhancement, hacktoberfest-accepted

#377 docs: info about tutorial
  README.md
  docs/getting_started/README.md
Labels: documentation, Skip-Changelog

#293 feat: add GeoVex embedding model
  .github/workflows/_tests.yml
  CHANGELOG.md
  examples/embedders/README.md
  examples/embedders/geovex_embedder.ipynb
  srai/embedders/__init__.py
  srai/embedders/_pytorch_stubs.py
  srai/embedders/geovex/__init__.py
  srai/embedders/geovex/dataset.py
  srai/embedders/geovex/embedder.py
  srai/embedders/geovex/model.py
  srai/h3.py
  srai/loaders/osm_loaders/_base.py
  srai/loaders/osm_loaders/osm_online_loader.py
  srai/loaders/osm_loaders/osm_pbf_loader.py
  srai/loaders/osm_loaders/osm_tile_loader.py
  srai/neighbourhoods/h3_neighbourhood.py
  tests/embedders/geovex/constants.py
  tests/embedders/geovex/generation.py
  tests/embedders/geovex/test_dataset.py
  tests/embedders/geovex/test_embedder.py
  tests/embedders/geovex/test_files/AL_10_batch_0.pt
  tests/embedders/geovex/test_files/AL_10_batch_1.pt
  tests/embedders/geovex/test_files/AL_10_batch_2.pt
  tests/embedders/geovex/test_files/AL_10_batch_3.pt
  tests/embedders/geovex/test_files/AL_10_encoder_forward_0.pt
  tests/embedders/geovex/test_files/AL_10_encoder_forward_1.pt
  tests/embedders/geovex/test_files/AL_10_encoder_forward_2.pt
  tests/embedders/geovex/test_files/AL_10_encoder_forward_3.pt
  tests/embedders/geovex/test_files/AL_10_features.parquet
  tests/embedders/geovex/test_files/AL_10_forward_0.pt
  tests/embedders/geovex/test_files/AL_10_forward_1.pt
  tests/embedders/geovex/test_files/AL_10_forward_2.pt
  tests/embedders/geovex/test_files/AL_10_forward_3.pt
  tests/embedders/geovex/test_files/AL_10_joint.parquet
  tests/embedders/geovex/test_files/AL_10_loss_0.pt
  tests/embedders/geovex/test_files/AL_10_loss_1.pt
  tests/embedders/geovex/test_files/AL_10_loss_2.pt
  tests/embedders/geovex/test_files/AL_10_loss_3.pt
  tests/embedders/geovex/test_files/AL_10_regions.parquet
  tests/embedders/geovex/test_files/AL_10_result.parquet
  tests/embedders/geovex/test_files/wro_9_batch_0.pt
  tests/embedders/geovex/test_files/wro_9_batch_1.pt
  tests/embedders/geovex/test_files/wro_9_encoder_forward_0.pt
  tests/embedders/geovex/test_files/wro_9_encoder_forward_1.pt
  tests/embedders/geovex/test_files/wro_9_features.parquet
  tests/embedders/geovex/test_files/wro_9_forward_0.pt
  tests/embedders/geovex/test_files/wro_9_forward_1.pt
  tests/embedders/geovex/test_files/wro_9_joint.parquet
  tests/embedders/geovex/test_files/wro_9_loss_0.pt
  tests/embedders/geovex/test_files/wro_9_loss_1.pt
  tests/embedders/geovex/test_files/wro_9_regions.parquet
  tests/embedders/geovex/test_files/wro_9_result.parquet
  tests/embedders/geovex/test_model.py
  tests/embedders/hex2vec/constants.py
  tests/embedders/hex2vec/generation.py
  tests/miscellaneous/test_optional_dependencies.py
Labels: enhancement, hacktoberfest-accepted

#381 feat: improve osm tags filter usability
  CHANGELOG.md
  CITATION.cff
  examples/embedders/geovex_embedder.ipynb
  pyproject.toml
  srai/__init__.py
  srai/embedders/contextual_count_embedder.py
  srai/embedders/count_embedder.py
  srai/embedders/geovex/embedder.py
  srai/embedders/hex2vec/embedder.py
  srai/loaders/osm_loaders/filters/geofabrik.py
  tests/embedders/test_contextual_count_embedder.py
  tests/embedders/test_count_embedder.py
Labels: enhancement

#394 ci: change gh-pages deployment flow
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  examples/loaders/osm_way_loader.ipynb
Labels: Skip-Changelog
