Repository kraina-ai/srai, pull requests merged in 2023-12, with the labels that each got.

#419 CI/CD: fix GH release on multiline commit
  .github/workflows/gh-release.yml
  pyproject.toml
Labels: bug, Skip-Changelog

#424 chore(CI/CD): bump version 0.6.1 -> 0.6.2
  CHANGELOG.md
  CITATION.cff
  pyproject.toml
  srai/__init__.py
Labels: release

#425 chore: lock mike version
  pdm.lock
  pyproject.toml
Labels: Skip-Changelog
